#!/usr/bin/env python3
"""Generate wire types, the column catalog, and field reference from JSON Schema."""
import argparse, json, pathlib, subprocess
from schema_profile import validate_profile, record_kinds

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "schema/records.schema.json"


def camel(name):
    return "".join(p.capitalize() for p in name.split("_"))


def generate(schema):
    validate_profile(schema)
    defs = schema["$defs"]
    kinds = record_kinds(schema)
    catalog = {
        "schema_version": "v1",
        "note": "Generated from schema/records.schema.json by tools/gen-schema.py.",
        "types": {
            "string": "utf8",
            "integer": "int64",
            "number": "float64",
            "boolean": "bool",
            "array of string": "list<utf8>",
            "array": "list<struct>",
        },
        "endpoints_element": {},
        "kinds": {},
    }
    rust = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// Generated by tools/gen-schema.py. Edit schema/records.schema.json.",
        "use serde::{Deserialize, Serialize};",
        "use serde_json::{Map, Value};",
        "use crate::Presence;",
        "",
    ]
    rust += [
        "/// Wire contract version emitted by producers using this schema.",
        f'pub const CONTRACT_VERSION: &str = {json.dumps(schema["x-contract-version"])};',
        "/// Content identity construction defined by the wire contract.",
        f'pub const CONTENT_CONSTRUCTION: &str = {json.dumps(schema["x-content-construction"])};',
    ]
    rust += [
        f'pub(crate) const RECORD_KINDS: &[&str] = &[{", ".join(json.dumps(k) for k in kinds)}];'
    ]
    docs = [
        "# Record fields",
        "",
        "Generated from `schema/records.schema.json`. See the specification for stream semantics.",
        "",
    ]
    for name, obj in defs.items():
        fields = {}
        rust += [
            f"/// Wire fields for `{name}`. Use [`crate::Record::decode`] for complete record validation.",
            "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]",
            f"pub struct {camel(name)} {{",
        ]
        docs += [
            f"## {name}",
            "",
            "| Field | JSON type | Presence | Description |",
            "|---|---|---|---|",
        ]
        for field, spec in obj["properties"].items():
            physical = spec["x-column-type"]
            presence = spec["x-presence"]
            fields[field] = {"type": physical, "presence": presence}
            if "const" in spec:
                fields[field]["const"] = spec["const"]
            docs.append(
                f"| `{field}` | `{spec['type']}` | {presence} | {spec.get('description','')} |"
            )
            if field == "kind":
                continue
            description = spec.get("description", f"The {field} field.")
            rust += [
                "    /// " + line.replace("[", "\\[").replace("]", "\\]")
                for line in description.splitlines()
            ]
            ty = {
                "utf8": "String",
                "int64": "i64",
                "float64": "f64",
                "bool": "bool",
                "list<utf8>": "Vec<String>",
                "list<struct>": "Vec<Endpoint>",
            }[physical]
            optional = field not in obj.get("required", [])
            nullable = isinstance(spec["type"], list) and "null" in spec["type"]
            if optional and nullable:
                ty = f"Presence<{ty}>"
                rust += [
                    '    #[serde(default, skip_serializing_if = "Presence::is_absent")]'
                ]
            elif optional or nullable:
                ty = f"Option<{ty}>"
                if optional:
                    rust += [
                        '    #[serde(default, skip_serializing_if = "Option::is_none")]'
                    ]
            rust += [f"    pub {field}: {ty},"]
        rust += [
            "    /// Extension fields. Serialization rejects names reserved by this structure.",
            f'    #[serde(flatten, serialize_with = "{camel(name)}::serialize_extensions")]',
            "    pub extensions: Map<String, Value>,",
            "}",
            "",
        ]
        reserved = ", ".join(json.dumps(field) for field in obj["properties"])
        rust += [
            f"impl {camel(name)} {{",
            f"    const RESERVED_FIELDS: &'static [&'static str] = &[{reserved}];",
            "    fn serialize_extensions<S: serde::Serializer>(extensions: &Map<String, Value>, serializer: S) -> Result<S::Ok, S::Error> {",
            '        crate::check_extensions(extensions, Self::RESERVED_FIELDS, "record").map_err(serde::ser::Error::custom)?;',
            "        extensions.serialize(serializer)",
            "    }",
            "    pub(crate) fn check_extensions(&self, path: &str) -> Result<(), crate::ValidationError> {",
            "        crate::check_extensions(&self.extensions, Self::RESERVED_FIELDS, path)?;",
        ]
        for field, spec in obj["properties"].items():
            if spec["x-column-type"] == "list<struct>":
                optional = field not in obj.get("required", [])
                iterator = (
                    f"self.{field}.iter().flatten()"
                    if optional
                    else f"self.{field}.iter()"
                )
                rust += [
                    f"        for (index, value) in {iterator}.enumerate() {{",
                    f'            value.check_extensions(&format!("{{path}}.{field}[{{index}}]"))?;',
                    "        }",
                ]
        rust += ["        Ok(())", "    }", "}", ""]
        docs += [""]
        if name == "Endpoint":
            catalog["endpoints_element"] = fields
        else:
            catalog["kinds"][name] = {"section": obj["x-section"], "fields": fields}
    rust += [
        "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]",
        '#[serde(tag = "kind")]',
        "/// Record kinds defined by this schema. Direct Serde decoding checks layout only.",
        "pub enum KnownRecord {",
    ]
    for kind in kinds:
        rust += [
            f"    /// The `{kind}` record.",
            f'    #[serde(rename = "{kind}")]',
            f"    {camel(kind)}({camel(kind)}),",
        ]
    rust += ["}", ""]
    rust += [
        "impl KnownRecord {",
        "    pub(crate) fn check_extensions(&self) -> Result<(), crate::ValidationError> {",
        "        match self {",
    ]
    rust += [
        f'Self::{camel(kind)}(record) => record.check_extensions("record"),'
        for kind in kinds
    ]
    rust += ["        }", "    }", "}"]
    formatted = subprocess.run(
        ["rustfmt", "--edition", "2021"],
        input="\n".join(rust),
        text=True,
        capture_output=True,
        check=True,
    ).stdout
    return {
        "crates/model/tests/structure.json": (
            ROOT / "conformance/structure/cases.json"
        ).read_text(),
        "conformance/schema/records.schema.json": json.dumps(schema, indent=2) + "\n",
        "crates/model/schema/records.schema.json": json.dumps(schema, indent=2) + "\n",
        "crates/model/schema/columns.json": json.dumps(catalog, indent=1) + "\n",
        "conformance/schema/records.json": json.dumps(catalog, indent=1) + "\n",
        "crates/model/src/generated.rs": formatted,
        "docs/record-fields.md": "\n".join(docs),
    }


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true")
    args = p.parse_args()
    for name, body in generate(json.loads(SOURCE.read_text())).items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != body:
                raise SystemExit(f"{name} is stale; run tools/gen-schema.py")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body)
    print(
        "Generated artifacts are current"
        if args.check
        else "Generated model, column catalog and field reference"
    )


if __name__ == "__main__":
    main()
