#!/usr/bin/env python3
"""Generate wire types, the column catalog, and field reference from JSON Schema."""
import argparse, json, pathlib, subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "schema/records.schema.json"


def camel(name):
    return "".join(p.capitalize() for p in name.split("_"))


def check_supported_profile(rule, path="schema", root=True):
    """Refuse schema keywords the bundled runtime validator does not implement."""
    supported = {
        "$schema",
        "$id",
        "title",
        "description",
        "oneOf",
        "$defs",
        "type",
        "properties",
        "required",
        "additionalProperties",
        "const",
        "minimum",
        "maximum",
        "items",
        "$ref",
        "allOf",
        "if",
        "then",
        "not",
    }
    if "oneOf" in rule and not root:
        raise SystemExit(f"{path}: oneOf is supported only for root record dispatch")
    for key in rule:
        if key not in supported and not key.startswith("x-"):
            raise SystemExit(f"{path}: unsupported validation keyword {key}")
    if rule.get("additionalProperties", True) is not True:
        raise SystemExit(f"{path}: extensions must remain forward compatible")
    if "$ref" in rule and not rule["$ref"].startswith("#/$defs/"):
        raise SystemExit(f"{path}: references must resolve inside this schema")
    for key in ("properties", "$defs"):
        for name, child in rule.get(key, {}).items():
            check_supported_profile(child, f"{path}.{name}", root=False)
    for key in ("oneOf", "allOf"):
        for child in rule.get(key, []):
            check_supported_profile(child, path, root=False)
    for key in ("items", "if", "then", "not"):
        if key in rule:
            check_supported_profile(rule[key], path, root=False)


def generate(schema):
    check_supported_profile(schema)
    defs = schema["$defs"]
    kinds = [r["$ref"].rsplit("/", 1)[1] for r in schema["oneOf"]]
    catalog = {
        "schema_version": "v1",
        "note": "Generated from schema/records.schema.json by tools/gen-schema.py.",
        "types": {
            "string": "utf8",
            "integer": "int64",
            "number": "float64",
            "boolean": "bool",
            "array of string": "list<utf8>",
            "array": "list<struct>",
        },
        "endpoints_element": {},
        "kinds": {},
    }
    rust = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// Generated by tools/gen-schema.py. Edit schema/records.schema.json.",
        "use serde::{Deserialize, Serialize};",
        "use serde_json::{Map, Value};",
        "use crate::Presence;",
        "",
    ]
    rust += [
        f'pub const CONTRACT_VERSION: &str = {json.dumps(schema["x-contract-version"])};',
        f'pub const CONTENT_CONSTRUCTION: &str = {json.dumps(schema["x-content-construction"])};',
    ]
    docs = [
        "# Record fields",
        "",
        "Generated from `schema/records.schema.json`. See the specification for stream semantics.",
        "",
    ]
    for name, obj in defs.items():
        fields = {}
        rust += [
            "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]",
            f"pub struct {camel(name)} {{",
        ]
        docs += [
            f"## {name}",
            "",
            "| Field | JSON type | Presence | Description |",
            "|---|---|---|---|",
        ]
        for field, spec in obj["properties"].items():
            physical = spec["x-column-type"]
            presence = spec["x-presence"]
            fields[field] = {"type": physical, "presence": presence}
            if "const" in spec:
                fields[field]["const"] = spec["const"]
            docs.append(
                f"| `{field}` | `{spec['type']}` | {presence} | {spec.get('description','')} |"
            )
            if field == "kind":
                continue
            ty = {
                "utf8": "String",
                "int64": "i64",
                "float64": "f64",
                "bool": "bool",
                "list<utf8>": "Vec<String>",
                "list<struct>": "Vec<Endpoint>",
            }[physical]
            optional = field not in obj.get("required", [])
            nullable = isinstance(spec["type"], list) and "null" in spec["type"]
            if optional and nullable:
                ty = f"Presence<{ty}>"
                rust += [
                    '    #[serde(default, skip_serializing_if = "Presence::is_absent")]'
                ]
            elif optional or nullable:
                ty = f"Option<{ty}>"
                if optional:
                    rust += [
                        '    #[serde(default, skip_serializing_if = "Option::is_none")]'
                    ]
            rust += [f"    pub {field}: {ty},"]
        rust += [
            "    #[serde(flatten)]",
            "    pub extensions: Map<String, Value>,",
            "}",
            "",
        ]
        docs += [""]
        if name == "Endpoint":
            catalog["endpoints_element"] = fields
        else:
            catalog["kinds"][name] = {"section": obj["x-section"], "fields": fields}
    rust += [
        "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]",
        '#[serde(tag = "kind")]',
        "pub enum KnownRecord {",
    ]
    for kind in kinds:
        rust += [
            f'    #[serde(rename = "{kind}")]',
            f"    {camel(kind)}({camel(kind)}),",
        ]
    rust += ["}", ""]
    formatted = subprocess.run(
        ["rustfmt", "--edition", "2021"],
        input="\n".join(rust),
        text=True,
        capture_output=True,
        check=True,
    ).stdout
    return {
        "crates/model/tests/structure.json": (
            ROOT / "conformance/structure/cases.json"
        ).read_text(),
        "conformance/schema/records.schema.json": json.dumps(schema, indent=2) + "\n",
        "crates/model/schema/records.schema.json": json.dumps(schema, indent=2) + "\n",
        "crates/model/schema/columns.json": json.dumps(catalog, indent=1) + "\n",
        "conformance/schema/records.json": json.dumps(catalog, indent=1) + "\n",
        "crates/model/src/generated.rs": formatted,
        "docs/record-fields.md": "\n".join(docs),
    }


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true")
    args = p.parse_args()
    for name, body in generate(json.loads(SOURCE.read_text())).items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != body:
                raise SystemExit(f"{name} is stale; run tools/gen-schema.py")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(body)
    print(
        "Generated artifacts are current"
        if args.check
        else "Generated model, column catalog and field reference"
    )


if __name__ == "__main__":
    main()
