// SPDX-License-Identifier: Apache-2.0
// Generated by tools/gen-schema.py. Edit schema/records.schema.json.
use crate::Presence;
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

pub const CONTRACT_VERSION: &str = "2.0";
pub const CONTENT_CONSTRUCTION: &str = "sha256-chain-128-v2";
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Endpoint {
    pub dropped: i64,
    pub endpoint: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_msg_at_ms: Option<f64>,
    pub msgs_seen: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub publisher_restarts: Option<i64>,
    pub source: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic: Option<String>,
    #[serde(flatten)]
    pub extensions: Map<String, Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentStart {
    pub at_ms: f64,
    pub agent_version: String,
    pub egress: String,
    pub endpoint_count: i64,
    pub max_payload_bytes: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub canary: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reuse_reporting: Option<String>,
    #[serde(flatten)]
    pub extensions: Map<String, Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentStop {
    pub at_ms: f64,
    pub reason: String,
    pub msgs_seen: i64,
    pub dropped: i64,
    pub oversized: i64,
    pub unknown_types: i64,
    pub events_ingested: i64,
    pub content_unresolved: i64,
    pub content_bridge_entries: i64,
    pub content_bridge_evicted: i64,
    pub publisher_restarts: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reuse_reporting: Option<String>,
    pub endpoints: Vec<Endpoint>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub canary: Option<String>,
    #[serde(flatten)]
    pub extensions: Map<String, Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Clear {
    pub at_ms: f64,
    pub instance_id: String,
    pub scope: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dp_rank: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_idx: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tier: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seq: Option<i64>,
    #[serde(flatten)]
    pub extensions: Map<String, Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Evict {
    pub at_ms: f64,
    pub instance_id: String,
    pub block_id: String,
    #[serde(default, skip_serializing_if = "Presence::is_absent")]
    pub tier: Presence<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dp_rank: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_idx: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub locality: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seq: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub epoch: Option<i64>,
    #[serde(flatten)]
    pub extensions: Map<String, Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Heartbeat {
    pub at_ms: f64,
    pub msgs_seen: i64,
    pub dropped: i64,
    pub oversized: i64,
    pub unknown_types: i64,
    pub events_ingested: i64,
    pub content_unresolved: i64,
    pub content_bridge_entries: i64,
    pub content_bridge_evicted: i64,
    pub publisher_restarts: i64,
    pub endpoints: Vec<Endpoint>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub canary: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reuse_reporting: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub noraw_scanned: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rss_bytes: Option<i64>,
    #[serde(flatten)]
    pub extensions: Map<String, Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HolderReset {
    pub at_ms: f64,
    pub instance_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dp_rank: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_idx: Option<i64>,
    pub boundary_ms: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seq: Option<i64>,
    #[serde(flatten)]
    pub extensions: Map<String, Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct IdentityRefused {
    pub at_ms: f64,
    pub instance_id: String,
    pub dp_rank: i64,
    pub group_idx: i64,
    pub refused: i64,
    pub window_start_ms: f64,
    pub window_end_ms: f64,
    #[serde(flatten)]
    pub extensions: Map<String, Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SegmentOpen {
    pub at_ms: f64,
    pub incarnation: String,
    pub segment_seq: i64,
    pub contract_version: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workload_class: Option<String>,
    pub heartbeat_secs: i64,
    pub max_segment_secs: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key_epoch: Option<i64>,
    #[serde(flatten)]
    pub extensions: Map<String, Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SegmentRecovered {
    pub at_ms: f64,
    pub attributed: bool,
    pub dropped_bytes: i64,
    #[serde(flatten)]
    pub extensions: Map<String, Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SegmentsDropped {
    pub at_ms: f64,
    pub incarnation: String,
    pub count: i64,
    pub first_seq: i64,
    pub last_seq: i64,
    pub first: String,
    pub last: String,
    #[serde(flatten)]
    pub extensions: Map<String, Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Store {
    pub at_ms: f64,
    pub instance_id: String,
    pub block_id: String,
    pub n_tokens: i64,
    pub tier: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dp_rank: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_idx: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_unknown: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub locality: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extra_keys: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lora_id: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lora_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spec_kind: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spec_sliding_window: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reused: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seq: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub epoch: Option<i64>,
    #[serde(flatten)]
    pub extensions: Map<String, Value>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum KnownRecord {
    #[serde(rename = "agent_start")]
    AgentStart(AgentStart),
    #[serde(rename = "agent_stop")]
    AgentStop(AgentStop),
    #[serde(rename = "clear")]
    Clear(Clear),
    #[serde(rename = "evict")]
    Evict(Evict),
    #[serde(rename = "heartbeat")]
    Heartbeat(Heartbeat),
    #[serde(rename = "holder_reset")]
    HolderReset(HolderReset),
    #[serde(rename = "identity_refused")]
    IdentityRefused(IdentityRefused),
    #[serde(rename = "segment_open")]
    SegmentOpen(SegmentOpen),
    #[serde(rename = "segment_recovered")]
    SegmentRecovered(SegmentRecovered),
    #[serde(rename = "segments_dropped")]
    SegmentsDropped(SegmentsDropped),
    #[serde(rename = "store")]
    Store(Store),
}
