// SPDX-License-Identifier: Apache-2.0
// Generated by tools/gen-schema.py. Edit schema/records.schema.json.
use crate::Presence;
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

/// Wire contract version emitted by producers using this schema.
pub const CONTRACT_VERSION: &str = "2.1";
/// Content identity construction defined by the wire contract.
pub const CONTENT_CONSTRUCTION: &str = "sha256-chain-128-v2";
pub(crate) const RECORD_KINDS: &[&str] = &[
    "agent_start",
    "agent_stop",
    "clear",
    "evict",
    "heartbeat",
    "holder_reset",
    "identity_refused",
    "segment_open",
    "segment_recovered",
    "segments_dropped",
    "store",
];
/// Wire fields for `Endpoint`. Use [`crate::Record::decode`] for complete record validation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Endpoint {
    /// Inbound messages known lost on this subscription.
    pub dropped: i64,
    /// Configured subscription endpoint.
    pub endpoint: String,
    /// Producer-clock timestamp of the last observed message, in milliseconds.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_msg_at_ms: Option<f64>,
    /// Inbound messages observed on this subscription.
    pub msgs_seen: i64,
    /// Sequence regressions observed on this subscription.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub publisher_restarts: Option<i64>,
    /// Operator-defined source name for this subscription.
    pub source: String,
    /// Configured subscription topic.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub topic: Option<String>,
    /// Extension fields. Serialization rejects names reserved by this structure.
    #[serde(flatten, serialize_with = "Endpoint::serialize_extensions")]
    pub extensions: Map<String, Value>,
}

impl Endpoint {
    const RESERVED_FIELDS: &'static [&'static str] = &[
        "dropped",
        "endpoint",
        "last_msg_at_ms",
        "msgs_seen",
        "publisher_restarts",
        "source",
        "topic",
    ];
    fn serialize_extensions<S: serde::Serializer>(
        extensions: &Map<String, Value>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        crate::check_extensions(extensions, Self::RESERVED_FIELDS, "record")
            .map_err(serde::ser::Error::custom)?;
        extensions.serialize(serializer)
    }
    pub(crate) fn check_extensions(&self, path: &str) -> Result<(), crate::ValidationError> {
        crate::check_extensions(&self.extensions, Self::RESERVED_FIELDS, path)?;
        Ok(())
    }
}

/// Wire fields for `agent_start`. Use [`crate::Record::decode`] for complete record validation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentStart {
    /// Producer clock.
    pub at_ms: f64,
    /// Producer version.
    pub agent_version: String,
    /// One of `pseudonymized` or `raw`. `raw` means identities are emitted unprotected and §3's key-space rules do not apply.
    pub egress: String,
    /// Subscriptions configured.
    pub endpoint_count: i64,
    /// Largest inbound engine message accepted.
    pub max_payload_bytes: i64,
    /// Present when identities are keyed (§3.4).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub canary: Option<String>,
    /// `none` \| `labelled` \| `unlabelled`; whether this producer's engine announces cache reuse as a `store`, and whether it can be told apart (§2.3).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reuse_reporting: Option<String>,
    /// Extension fields. Serialization rejects names reserved by this structure.
    #[serde(flatten, serialize_with = "AgentStart::serialize_extensions")]
    pub extensions: Map<String, Value>,
}

impl AgentStart {
    const RESERVED_FIELDS: &'static [&'static str] = &[
        "kind",
        "at_ms",
        "agent_version",
        "egress",
        "endpoint_count",
        "max_payload_bytes",
        "canary",
        "reuse_reporting",
    ];
    fn serialize_extensions<S: serde::Serializer>(
        extensions: &Map<String, Value>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        crate::check_extensions(extensions, Self::RESERVED_FIELDS, "record")
            .map_err(serde::ser::Error::custom)?;
        extensions.serialize(serializer)
    }
    pub(crate) fn check_extensions(&self, path: &str) -> Result<(), crate::ValidationError> {
        crate::check_extensions(&self.extensions, Self::RESERVED_FIELDS, path)?;
        Ok(())
    }
}

/// Wire fields for `agent_stop`. Use [`crate::Record::decode`] for complete record validation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AgentStop {
    /// Producer clock.
    pub at_ms: f64,
    /// Why the run ended.
    pub reason: String,
    /// Inbound messages observed on this subscription.
    pub msgs_seen: i64,
    /// Inbound messages known lost on this subscription.
    pub dropped: i64,
    /// Inbound messages refused for size.
    pub oversized: i64,
    /// Inbound messages of unmodelled type.
    pub unknown_types: i64,
    /// Events that reached the record model.
    pub events_ingested: i64,
    /// Records emitted with no `content_id`, one per omission (§3.1).
    pub content_unresolved: i64,
    /// Identity-derivation state size (the producer's view of the resident set).
    pub content_bridge_entries: i64,
    /// Identity promises refused at the declared capacity; nonzero means some evicts will not resolve, each window also declared via `identity_refused`.
    pub content_bridge_evicted: i64,
    /// Sequence regressions observed on this subscription; the envelope's `publisher_restarts` is their sum, and `holder_reset` (§2.3) is the record a reader acts on.
    pub publisher_restarts: i64,
    /// `none` \| `labelled` \| `unlabelled`; whether this producer's engine announces cache reuse as a `store`, and whether it can be told apart (§2.3).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reuse_reporting: Option<String>,
    /// Per-subscription statistics.
    pub endpoints: Vec<Endpoint>,
    /// Present when identities are keyed (§3.4).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub canary: Option<String>,
    /// Extension fields. Serialization rejects names reserved by this structure.
    #[serde(flatten, serialize_with = "AgentStop::serialize_extensions")]
    pub extensions: Map<String, Value>,
}

impl AgentStop {
    const RESERVED_FIELDS: &'static [&'static str] = &[
        "kind",
        "at_ms",
        "reason",
        "msgs_seen",
        "dropped",
        "oversized",
        "unknown_types",
        "events_ingested",
        "content_unresolved",
        "content_bridge_entries",
        "content_bridge_evicted",
        "publisher_restarts",
        "reuse_reporting",
        "endpoints",
        "canary",
    ];
    fn serialize_extensions<S: serde::Serializer>(
        extensions: &Map<String, Value>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        crate::check_extensions(extensions, Self::RESERVED_FIELDS, "record")
            .map_err(serde::ser::Error::custom)?;
        extensions.serialize(serializer)
    }
    pub(crate) fn check_extensions(&self, path: &str) -> Result<(), crate::ValidationError> {
        crate::check_extensions(&self.extensions, Self::RESERVED_FIELDS, path)?;
        for (index, value) in self.endpoints.iter().enumerate() {
            value.check_extensions(&format!("{path}.endpoints[{index}]"))?;
        }
        Ok(())
    }
}

/// Wire fields for `clear`. Use [`crate::Record::decode`] for complete record validation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Clear {
    /// Engine clock.
    pub at_ms: f64,
    /// The engine process holding this cache, named by the operator (§3.2).
    pub instance_id: String,
    /// What was cleared, for example `all`.
    pub scope: String,
    /// The data parallel worker the clear applies to; **absent means the wire declared none and the clear is global across workers** (§3.2 and the note below).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dp_rank: Option<i64>,
    /// Cache group affected by the clear. Omission applies the clear across all groups.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_idx: Option<i64>,
    /// Storage tier the clear applied to; **absent means the clear is global across tiers**.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tier: Option<String>,
    /// Transport sequence of the message that carried this event.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seq: Option<i64>,
    /// Extension fields. Serialization rejects names reserved by this structure.
    #[serde(flatten, serialize_with = "Clear::serialize_extensions")]
    pub extensions: Map<String, Value>,
}

impl Clear {
    const RESERVED_FIELDS: &'static [&'static str] = &[
        "kind",
        "at_ms",
        "instance_id",
        "scope",
        "dp_rank",
        "group_idx",
        "tier",
        "seq",
    ];
    fn serialize_extensions<S: serde::Serializer>(
        extensions: &Map<String, Value>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        crate::check_extensions(extensions, Self::RESERVED_FIELDS, "record")
            .map_err(serde::ser::Error::custom)?;
        extensions.serialize(serializer)
    }
    pub(crate) fn check_extensions(&self, path: &str) -> Result<(), crate::ValidationError> {
        crate::check_extensions(&self.extensions, Self::RESERVED_FIELDS, path)?;
        Ok(())
    }
}

/// Wire fields for `evict`. Use [`crate::Record::decode`] for complete record validation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Evict {
    /// Engine clock.
    pub at_ms: f64,
    /// The engine process whose cache the block left (§3.2).
    pub instance_id: String,
    /// Engine-local identity (§3.1), the same value its `store` carried.
    pub block_id: String,
    /// Storage tier the block left. A block offloaded to another tier is evicted from the one it left.
    #[serde(default, skip_serializing_if = "Presence::is_absent")]
    pub tier: Presence<String>,
    /// The data parallel worker within that instance (§3.2).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dp_rank: Option<i64>,
    /// The cache group within that worker (§3.2).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_idx: Option<i64>,
    /// Portable identity (§3.1), resolved from the producer’s identity state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content_id: Option<String>,
    /// `LOCAL` or `REMOTE`, relative to the publishing holder.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub locality: Option<String>,
    /// Transport sequence of the message that carried this event.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seq: Option<i64>,
    /// Pseudonymization key epoch.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub epoch: Option<i64>,
    /// Optional engine-emitted backend identity, scoped to publisher incarnation, rank, group and tier. Pseudonymized at egress.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backend_id: Option<String>,
    /// Extension fields. Serialization rejects names reserved by this structure.
    #[serde(flatten, serialize_with = "Evict::serialize_extensions")]
    pub extensions: Map<String, Value>,
}

impl Evict {
    const RESERVED_FIELDS: &'static [&'static str] = &[
        "kind",
        "at_ms",
        "instance_id",
        "block_id",
        "tier",
        "dp_rank",
        "group_idx",
        "content_id",
        "locality",
        "seq",
        "epoch",
        "backend_id",
    ];
    fn serialize_extensions<S: serde::Serializer>(
        extensions: &Map<String, Value>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        crate::check_extensions(extensions, Self::RESERVED_FIELDS, "record")
            .map_err(serde::ser::Error::custom)?;
        extensions.serialize(serializer)
    }
    pub(crate) fn check_extensions(&self, path: &str) -> Result<(), crate::ValidationError> {
        crate::check_extensions(&self.extensions, Self::RESERVED_FIELDS, path)?;
        Ok(())
    }
}

/// Wire fields for `heartbeat`. Use [`crate::Record::decode`] for complete record validation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Heartbeat {
    /// Producer clock.
    pub at_ms: f64,
    /// Inbound messages observed on this subscription.
    pub msgs_seen: i64,
    /// Inbound messages known lost on this subscription.
    pub dropped: i64,
    /// Inbound messages refused for size.
    pub oversized: i64,
    /// Inbound messages of unmodelled type.
    pub unknown_types: i64,
    /// Events that reached the record model.
    pub events_ingested: i64,
    /// Records emitted with no `content_id`, one per omission (§3.1).
    pub content_unresolved: i64,
    /// Identity-derivation state size (the producer's view of the resident set).
    pub content_bridge_entries: i64,
    /// Identity promises refused at the declared capacity; nonzero means some evicts will not resolve, each window also declared via `identity_refused`.
    pub content_bridge_evicted: i64,
    /// Sequence regressions observed on this subscription; the envelope's `publisher_restarts` is their sum, and `holder_reset` (§2.3) is the record a reader acts on.
    pub publisher_restarts: i64,
    /// Per-subscription statistics.
    pub endpoints: Vec<Endpoint>,
    /// Present when identities are keyed (§3.4).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub canary: Option<String>,
    /// `none` \| `labelled` \| `unlabelled`; whether this producer's engine announces cache reuse as a `store`, and whether it can be told apart (§2.3).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reuse_reporting: Option<String>,
    /// Values checked by the producer's egress guard.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub noraw_scanned: Option<i64>,
    /// Producer resident memory.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rss_bytes: Option<i64>,
    /// Extension fields. Serialization rejects names reserved by this structure.
    #[serde(flatten, serialize_with = "Heartbeat::serialize_extensions")]
    pub extensions: Map<String, Value>,
}

impl Heartbeat {
    const RESERVED_FIELDS: &'static [&'static str] = &[
        "kind",
        "at_ms",
        "msgs_seen",
        "dropped",
        "oversized",
        "unknown_types",
        "events_ingested",
        "content_unresolved",
        "content_bridge_entries",
        "content_bridge_evicted",
        "publisher_restarts",
        "endpoints",
        "canary",
        "reuse_reporting",
        "noraw_scanned",
        "rss_bytes",
    ];
    fn serialize_extensions<S: serde::Serializer>(
        extensions: &Map<String, Value>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        crate::check_extensions(extensions, Self::RESERVED_FIELDS, "record")
            .map_err(serde::ser::Error::custom)?;
        extensions.serialize(serializer)
    }
    pub(crate) fn check_extensions(&self, path: &str) -> Result<(), crate::ValidationError> {
        crate::check_extensions(&self.extensions, Self::RESERVED_FIELDS, path)?;
        for (index, value) in self.endpoints.iter().enumerate() {
            value.check_extensions(&format!("{path}.endpoints[{index}]"))?;
        }
        Ok(())
    }
}

/// Wire fields for `holder_reset`. Use [`crate::Record::decode`] for complete record validation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HolderReset {
    /// Producer clock at detection (§2.6).
    pub at_ms: f64,
    /// The engine the regressed source observes (§3.2).
    pub instance_id: String,
    /// The worker whose publisher regressed; **absent means the source hosts every rank and the reset is global across workers**.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dp_rank: Option<i64>,
    /// Cache group affected by the reset. Omit this field for a publisher sequence regression, which resets all groups.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_idx: Option<i64>,
    /// **engine clock**: the earliest event timestamp in the regressed message; the instant the reset is ordered at.
    pub boundary_ms: f64,
    /// The regressed sequence number, as the wire carried it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seq: Option<i64>,
    /// Extension fields. Serialization rejects names reserved by this structure.
    #[serde(flatten, serialize_with = "HolderReset::serialize_extensions")]
    pub extensions: Map<String, Value>,
}

impl HolderReset {
    const RESERVED_FIELDS: &'static [&'static str] = &[
        "kind",
        "at_ms",
        "instance_id",
        "dp_rank",
        "group_idx",
        "boundary_ms",
        "seq",
    ];
    fn serialize_extensions<S: serde::Serializer>(
        extensions: &Map<String, Value>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        crate::check_extensions(extensions, Self::RESERVED_FIELDS, "record")
            .map_err(serde::ser::Error::custom)?;
        extensions.serialize(serializer)
    }
    pub(crate) fn check_extensions(&self, path: &str) -> Result<(), crate::ValidationError> {
        crate::check_extensions(&self.extensions, Self::RESERVED_FIELDS, path)?;
        Ok(())
    }
}

/// Wire fields for `identity_refused`. Use [`crate::Record::decode`] for complete record validation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct IdentityRefused {
    /// Producer clock.
    pub at_ms: f64,
    /// The affected instance (§3.2).
    pub instance_id: String,
    /// The affected worker.
    pub dp_rank: i64,
    /// The affected cache group.
    pub group_idx: i64,
    /// Stores denied an identity in the window.
    pub refused: i64,
    /// **engine clock**: first refused store.
    pub window_start_ms: f64,
    /// **engine clock**: last refused store.
    pub window_end_ms: f64,
    /// Extension fields. Serialization rejects names reserved by this structure.
    #[serde(flatten, serialize_with = "IdentityRefused::serialize_extensions")]
    pub extensions: Map<String, Value>,
}

impl IdentityRefused {
    const RESERVED_FIELDS: &'static [&'static str] = &[
        "kind",
        "at_ms",
        "instance_id",
        "dp_rank",
        "group_idx",
        "refused",
        "window_start_ms",
        "window_end_ms",
    ];
    fn serialize_extensions<S: serde::Serializer>(
        extensions: &Map<String, Value>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        crate::check_extensions(extensions, Self::RESERVED_FIELDS, "record")
            .map_err(serde::ser::Error::custom)?;
        extensions.serialize(serializer)
    }
    pub(crate) fn check_extensions(&self, path: &str) -> Result<(), crate::ValidationError> {
        crate::check_extensions(&self.extensions, Self::RESERVED_FIELDS, path)?;
        Ok(())
    }
}

/// Wire fields for `segment_open`. Use [`crate::Record::decode`] for complete record validation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SegmentOpen {
    /// Producer clock.
    pub at_ms: f64,
    /// Identifies one run of one producer (§4.2).
    pub incarnation: String,
    /// Position in that incarnation's sequence, from zero.
    pub segment_seq: i64,
    /// The version of this contract the segment conforms to (§6.1).
    pub contract_version: String,
    /// Purpose of this producer’s traffic, in the operator's vocabulary (§2.7).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workload_class: Option<String>,
    /// Declared heartbeat interval (§5.8).
    pub heartbeat_secs: i64,
    /// Declared maximum segment age (§5.8).
    pub max_segment_secs: i64,
    /// Present when identities are keyed (§3.3).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key_epoch: Option<i64>,
    /// Extension fields. Serialization rejects names reserved by this structure.
    #[serde(flatten, serialize_with = "SegmentOpen::serialize_extensions")]
    pub extensions: Map<String, Value>,
}

impl SegmentOpen {
    const RESERVED_FIELDS: &'static [&'static str] = &[
        "kind",
        "at_ms",
        "incarnation",
        "segment_seq",
        "contract_version",
        "workload_class",
        "heartbeat_secs",
        "max_segment_secs",
        "key_epoch",
    ];
    fn serialize_extensions<S: serde::Serializer>(
        extensions: &Map<String, Value>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        crate::check_extensions(extensions, Self::RESERVED_FIELDS, "record")
            .map_err(serde::ser::Error::custom)?;
        extensions.serialize(serializer)
    }
    pub(crate) fn check_extensions(&self, path: &str) -> Result<(), crate::ValidationError> {
        crate::check_extensions(&self.extensions, Self::RESERVED_FIELDS, path)?;
        Ok(())
    }
}

/// Wire fields for `segment_recovered`. Use [`crate::Record::decode`] for complete record validation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SegmentRecovered {
    /// Producer clock.
    pub at_ms: f64,
    /// Whether the unfinished segment's own identity was readable.
    pub attributed: bool,
    /// Bytes discarded: the trailing incomplete record of an attributed recovery, or the whole unattributable file.
    pub dropped_bytes: i64,
    /// Extension fields. Serialization rejects names reserved by this structure.
    #[serde(flatten, serialize_with = "SegmentRecovered::serialize_extensions")]
    pub extensions: Map<String, Value>,
}

impl SegmentRecovered {
    const RESERVED_FIELDS: &'static [&'static str] =
        &["kind", "at_ms", "attributed", "dropped_bytes"];
    fn serialize_extensions<S: serde::Serializer>(
        extensions: &Map<String, Value>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        crate::check_extensions(extensions, Self::RESERVED_FIELDS, "record")
            .map_err(serde::ser::Error::custom)?;
        extensions.serialize(serializer)
    }
    pub(crate) fn check_extensions(&self, path: &str) -> Result<(), crate::ValidationError> {
        crate::check_extensions(&self.extensions, Self::RESERVED_FIELDS, path)?;
        Ok(())
    }
}

/// Wire fields for `segments_dropped`. Use [`crate::Record::decode`] for complete record validation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SegmentsDropped {
    /// Producer clock.
    pub at_ms: f64,
    /// The run whose data is gone, not the run that reclaimed it.
    pub incarnation: String,
    /// Segments reclaimed.
    pub count: i64,
    /// Lowest `segment_seq` reclaimed.
    pub first_seq: i64,
    /// Highest `segment_seq` reclaimed.
    pub last_seq: i64,
    /// Filename of the first segment reclaimed.
    pub first: String,
    /// Filename of the last segment reclaimed.
    pub last: String,
    /// Extension fields. Serialization rejects names reserved by this structure.
    #[serde(flatten, serialize_with = "SegmentsDropped::serialize_extensions")]
    pub extensions: Map<String, Value>,
}

impl SegmentsDropped {
    const RESERVED_FIELDS: &'static [&'static str] = &[
        "kind",
        "at_ms",
        "incarnation",
        "count",
        "first_seq",
        "last_seq",
        "first",
        "last",
    ];
    fn serialize_extensions<S: serde::Serializer>(
        extensions: &Map<String, Value>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        crate::check_extensions(extensions, Self::RESERVED_FIELDS, "record")
            .map_err(serde::ser::Error::custom)?;
        extensions.serialize(serializer)
    }
    pub(crate) fn check_extensions(&self, path: &str) -> Result<(), crate::ValidationError> {
        crate::check_extensions(&self.extensions, Self::RESERVED_FIELDS, path)?;
        Ok(())
    }
}

/// Wire fields for `store`. Use [`crate::Record::decode`] for complete record validation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Store {
    /// Engine clock.
    pub at_ms: f64,
    /// The engine process holding this cache, named by the operator (§3.2).
    pub instance_id: String,
    /// Engine-local identity (§3.1).
    pub block_id: String,
    /// Tokens the block holds.
    pub n_tokens: i64,
    /// Storage tier, for example `GPU`.
    pub tier: Option<String>,
    /// The data parallel worker within that instance, which holds its own independent cache (§3.2).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dp_rank: Option<i64>,
    /// The cache group within that worker. Groups hash independently (§3.2).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_idx: Option<i64>,
    /// Portable identity (§3.1). Absent where the producer could not derive one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content_id: Option<String>,
    /// The preceding block in this block's prefix chain.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    /// True when the parent exists but its portable identity could not be resolved. Omit `parent_id` in this case.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_unknown: Option<bool>,
    /// `LOCAL` or `REMOTE`, relative to the publishing holder.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub locality: Option<String>,
    /// Additional inputs to this block's identity beyond its tokens, for example a cache salt or a multimodal content hash. Operator controlled text, so each element is pseudonymized independently.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extra_keys: Option<Vec<String>>,
    /// Adapter identifier.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lora_id: Option<i64>,
    /// Adapter name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lora_name: Option<String>,
    /// Attention kind, for example `full_attention`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spec_kind: Option<String>,
    /// The sliding-window size of this block's cache group, where the engine declares one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spec_sliding_window: Option<i64>,
    /// This record reports a block already cached rather than a fresh insertion. Only under `reuse_reporting: "labelled"` (§2.4).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reused: Option<bool>,
    /// Transport sequence of the message that carried this event.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub seq: Option<i64>,
    /// Pseudonymization key epoch.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub epoch: Option<i64>,
    /// Optional engine-emitted backend identity, scoped to publisher incarnation, rank, group and tier. Pseudonymized at egress.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backend_id: Option<String>,
    /// Extension fields. Serialization rejects names reserved by this structure.
    #[serde(flatten, serialize_with = "Store::serialize_extensions")]
    pub extensions: Map<String, Value>,
}

impl Store {
    const RESERVED_FIELDS: &'static [&'static str] = &[
        "kind",
        "at_ms",
        "instance_id",
        "block_id",
        "n_tokens",
        "tier",
        "dp_rank",
        "group_idx",
        "content_id",
        "parent_id",
        "parent_unknown",
        "locality",
        "extra_keys",
        "lora_id",
        "lora_name",
        "spec_kind",
        "spec_sliding_window",
        "reused",
        "seq",
        "epoch",
        "backend_id",
    ];
    fn serialize_extensions<S: serde::Serializer>(
        extensions: &Map<String, Value>,
        serializer: S,
    ) -> Result<S::Ok, S::Error> {
        crate::check_extensions(extensions, Self::RESERVED_FIELDS, "record")
            .map_err(serde::ser::Error::custom)?;
        extensions.serialize(serializer)
    }
    pub(crate) fn check_extensions(&self, path: &str) -> Result<(), crate::ValidationError> {
        crate::check_extensions(&self.extensions, Self::RESERVED_FIELDS, path)?;
        Ok(())
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind")]
/// Record kinds defined by this schema. Direct Serde decoding checks layout only.
pub enum KnownRecord {
    /// The `agent_start` record.
    #[serde(rename = "agent_start")]
    AgentStart(AgentStart),
    /// The `agent_stop` record.
    #[serde(rename = "agent_stop")]
    AgentStop(AgentStop),
    /// The `clear` record.
    #[serde(rename = "clear")]
    Clear(Clear),
    /// The `evict` record.
    #[serde(rename = "evict")]
    Evict(Evict),
    /// The `heartbeat` record.
    #[serde(rename = "heartbeat")]
    Heartbeat(Heartbeat),
    /// The `holder_reset` record.
    #[serde(rename = "holder_reset")]
    HolderReset(HolderReset),
    /// The `identity_refused` record.
    #[serde(rename = "identity_refused")]
    IdentityRefused(IdentityRefused),
    /// The `segment_open` record.
    #[serde(rename = "segment_open")]
    SegmentOpen(SegmentOpen),
    /// The `segment_recovered` record.
    #[serde(rename = "segment_recovered")]
    SegmentRecovered(SegmentRecovered),
    /// The `segments_dropped` record.
    #[serde(rename = "segments_dropped")]
    SegmentsDropped(SegmentsDropped),
    /// The `store` record.
    #[serde(rename = "store")]
    Store(Store),
}

impl KnownRecord {
    pub(crate) fn check_extensions(&self) -> Result<(), crate::ValidationError> {
        match self {
            Self::AgentStart(record) => record.check_extensions("record"),
            Self::AgentStop(record) => record.check_extensions("record"),
            Self::Clear(record) => record.check_extensions("record"),
            Self::Evict(record) => record.check_extensions("record"),
            Self::Heartbeat(record) => record.check_extensions("record"),
            Self::HolderReset(record) => record.check_extensions("record"),
            Self::IdentityRefused(record) => record.check_extensions("record"),
            Self::SegmentOpen(record) => record.check_extensions("record"),
            Self::SegmentRecovered(record) => record.check_extensions("record"),
            Self::SegmentsDropped(record) => record.check_extensions("record"),
            Self::Store(record) => record.check_extensions("record"),
        }
    }
}
